/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EHRmain } from "./EHRmain";
export * as factories from "./factories";
export { EHRmain__factory } from "./factories/EHRmain__factory";
